### ISSUE TITLE
 Custom usage of It::Parser and optional string escaping

### ISSUE THREAD

**Issue by andi-dev** [iGEL/it#24]
I have a situation where I would like to make use of It's link / tag interpolation, without using the it helper.
More specifically the project already uses a custom 'translate'-helper with added functionality.

I thus decided to use the It::Parser directly from our helper, which works fine. Yet it is undocumented api, so my suggestion would be to officially document that scenario. I think I could do so and create a pull request.

Second I have a problem with It escaping the strings, as we're already using a different approach of sanitising our translations. Because we want to keep html characters like &amp; or &shy; we're using the         Rails::Html::WhiteListSanitizer.new.sanitize(str, tags: []).

'It' however is using Erb::Util.h which escapes those html entities. Would you accept a pull request that optionally disables escaping? As long as 'it' still returns String instead of ActiveSupport::SafeBuffer, current rails versions would still escape them, unless developers choose to mark them as html_safe.

**Comment by iGEL** [comment]
Hi @andi-dev! 

I assume, you have seen `It.it`, but it doesn't solve your issue, since it's still calling `I18n.t`, correct? I would not mention `It::Parser` in the README, as I would consider a less common use case, but I'd be fine with a PR that adds inline documentation with possible references from `It::Helper.it` and `It.it`. That way we would state that it's not a private API. WDYT?

To the html escaping: `it` uses `Erb::Util.h`, but this is a [Rails addition](https://api.rubyonrails.org/classes/ERB/Util.html#method-c-html_escape), thus handles `ActiveSupport::SafeBuffer` properly. If you mark the string as html safe, it won't be escaped again. Does that work in your case?

**Comment by andi-dev** [comment]
Hi @iGEL , thanks for the quick reply! Yes, It.it only accepts an i18n identifier, I already have a translated string at this point. Yes, I think adding inline documentation should be enough, someone who is having a less common use case like me will likely also have a look into the code.

I will send you a pull request some time this week.

And, yes, If i already pass an ActiveSupport::SafeBuffer it works! Thank you 👍
